import type {
  AgeGroup,
  GoalKey,
  ProfessionalRecord,
  UserRole,
} from "@/lib/app-types";

export const roleOptions: Array<{ value: UserRole; label: string }> = [
  { value: "parent-caregiver", label: "Parent or caregiver" },
  { value: "self-advocate", label: "Autistic self-advocate" },
  { value: "professional", label: "Professional" },
];

export const ageGroupOptions: Array<{ value: AgeGroup; label: string }> = [
  { value: "early-years", label: "Early years (0-5)" },
  { value: "school-age", label: "School age (6-12)" },
  { value: "teen", label: "Teen years (13-17)" },
  { value: "adult", label: "Adult life (18+)" },
  { value: "caregiver", label: "Family and caregiver support" },
];

export const goalOptions: Array<{ value: GoalKey; label: string }> = [
  { value: "early-support", label: "Early support" },
  { value: "education", label: "Education and school planning" },
  { value: "sensory-support", label: "Sensory support" },
  { value: "social-growth", label: "Social growth and connection" },
  { value: "employment", label: "Employment" },
  { value: "independent-living", label: "Independent living" },
  { value: "caregiver-wellness", label: "Caregiver wellness" },
];

export const communityTopicOptions = [
  "Parent Support",
  "Self-Advocacy",
  "School and Therapy",
  "Sensory and Lifestyle",
  "Adult Independence",
] as const;

export const resourceSeeds: Array<{
  id: string;
  title: string;
  summary: string;
  collectionName: string;
  category: string;
  audience: string;
  ageGroup: AgeGroup | "all";
  tags: GoalKey[];
  locationScope: string;
  verified: boolean;
  organization: string;
  href: string;
  regionTags: string[];
}> = [
  {
    id: "taca-newly-diagnosed-autism-initiative",
    title: "TACA Newly Diagnosed Autism Initiative",
    summary:
      "A practical starting point for families preparing for early intervention, treatments, and next-step support after a new diagnosis.",
    collectionName: "Family Start Here",
    category: "New diagnosis",
    audience: "Parents and caregivers",
    ageGroup: "early-years",
    tags: ["early-support", "caregiver-wellness"],
    locationScope: "Available nationwide",
    verified: true,
    organization: "The Autism Community in Action",
    href: "https://tacanow.org/resource/newly-diagnosed-autism-initiative/",
    regionTags: ["nationwide"],
  },
  {
    id: "autism-speaks-first-concern-to-action",
    title: "Autism Speaks First Concern to Action Tool Kit",
    summary:
      "A step-by-step guide for families who are worried about development and want help moving from concern to evaluation and action.",
    collectionName: "Family Start Here",
    category: "Planning",
    audience: "Parents and caregivers",
    ageGroup: "early-years",
    tags: ["early-support", "education"],
    locationScope: "Available nationwide",
    verified: true,
    organization: "Autism Speaks",
    href: "https://www.autismspeaks.org/tool-kit/first-concern-action-tool-kit",
    regionTags: ["nationwide"],
  },
  {
    id: "autism-speaks-100-day-school-age-kit",
    title: "Autism Speaks 100 Day Kit for School Age Children",
    summary:
      "A guide for families of school-age children who want a clearer plan for school support, services, and what to do next.",
    collectionName: "School and Learning",
    category: "Education",
    audience: "Parents, caregivers, and educators",
    ageGroup: "school-age",
    tags: ["education", "caregiver-wellness", "early-support"],
    locationScope: "Available nationwide",
    verified: true,
    organization: "Autism Speaks",
    href: "https://docs.autismspeaks.org/100-day-kit-school-age-children/introduction",
    regionTags: ["nationwide"],
  },
  {
    id: "family-focus-resource-center",
    title: "Family Focus Resource Center",
    summary:
      "Parent mentoring, IEP education, advocacy support, workshops, and family resource navigation for families across the Antelope Valley and surrounding communities.",
    collectionName: "School and Learning",
    category: "Family support",
    audience: "Parents, caregivers, and educators",
    ageGroup: "caregiver",
    tags: ["education", "caregiver-wellness", "social-growth"],
    locationScope: "Antelope Valley, San Fernando Valley, and Santa Clarita",
    verified: true,
    organization: "CSUN Family Focus Resource Center",
    href: "https://engage.csun.edu/colleges/education/fund-detail-family-focus-resource-center-",
    regionTags: [
      "antelope-valley",
      "los-angeles-county",
      "southern-california",
      "california",
    ],
  },
  {
    id: "nlacrc-partners-and-advocacy-groups",
    title: "NLACRC Partners and Advocacy Groups",
    summary:
      "A regional directory of support groups, advocacy organizations, and family connections hosted through North Los Angeles County Regional Center.",
    collectionName: "Family and Caregivers",
    category: "Community",
    audience: "Families, self-advocates, and caregivers",
    ageGroup: "all",
    tags: ["social-growth", "caregiver-wellness", "independent-living"],
    locationScope: "North Los Angeles County and Antelope Valley",
    verified: true,
    organization: "North Los Angeles County Regional Center",
    href: "https://www.nlacrc.org/get-involved/advocacy/partners-advocacy-groups/",
    regionTags: [
      "antelope-valley",
      "los-angeles-county",
      "southern-california",
      "california",
    ],
  },
  {
    id: "easterseals-southern-california-autism-services",
    title: "Easterseals Southern California Autism Services",
    summary:
      "Regional autism services that include family support, developmental services, and help connecting with programs across Southern California.",
    collectionName: "Family Start Here",
    category: "Therapies",
    audience: "Children, adults, and families",
    ageGroup: "all",
    tags: ["early-support", "sensory-support", "caregiver-wellness"],
    locationScope: "Southern California",
    verified: true,
    organization: "Easterseals Southern California",
    href: "https://www.easterseals.com/southerncal/support-and-education/autism/index-1.html",
    regionTags: ["southern-california", "orange-county", "california"],
  },
  {
    id: "autism-speaks-resource-guide",
    title: "Autism Speaks Resource Guide",
    summary:
      "A searchable directory for services, supports, and autism-related organizations by ZIP code, state, and service type.",
    collectionName: "Family and Caregivers",
    category: "Directory",
    audience: "Families, self-advocates, and professionals",
    ageGroup: "all",
    tags: ["early-support", "education", "social-growth", "independent-living"],
    locationScope: "Nationwide with local search",
    verified: true,
    organization: "Autism Speaks",
    href: "https://www.autismspeaks.org/resource-guide",
    regionTags: ["nationwide"],
  },
  {
    id: "autism-speaks-transition-tool-kit",
    title: "Autism Speaks Transition to Adulthood Tool Kit",
    summary:
      "Transition planning support for self-advocacy, employment, education, housing, healthcare, and community living.",
    collectionName: "Teen and Transition",
    category: "Transition planning",
    audience: "Teens, young adults, and families",
    ageGroup: "teen",
    tags: ["education", "employment", "independent-living", "social-growth"],
    locationScope: "Available nationwide",
    verified: true,
    organization: "Autism Speaks",
    href: "https://www.autismspeaks.org/toolkit/transition-tool-kit",
    regionTags: ["nationwide"],
  },
  {
    id: "autism-speaks-employment-tool-kit",
    title: "Autism Speaks Employment Tool Kit",
    summary:
      "Employment planning support with guidance on career options, resumes, interviews, accommodations, and workplace rights.",
    collectionName: "Adult Independence",
    category: "Employment",
    audience: "Autistic adults and job seekers",
    ageGroup: "adult",
    tags: ["employment", "independent-living", "social-growth"],
    locationScope: "Available nationwide",
    verified: true,
    organization: "Autism Speaks",
    href: "https://www.autismspeaks.org/tool-kit/employment-tool-kit",
    regionTags: ["nationwide"],
  },
  {
    id: "adult-autism-diagnosis-tool-kit",
    title: "Adult Autism Diagnosis Tool Kit",
    summary:
      "A guide created with autistic adults to help with diagnosis questions, next steps, legal rights, and supports in adulthood.",
    collectionName: "Adult Independence",
    category: "Adult support",
    audience: "Autistic adults and families",
    ageGroup: "adult",
    tags: ["independent-living", "social-growth", "employment"],
    locationScope: "Available nationwide",
    verified: true,
    organization: "Autism Speaks",
    href: "https://www.autismspeaks.org/tool-kit/adult-autism-diagnosis-tool-kit",
    regionTags: ["nationwide"],
  },
  {
    id: "asan-autism-safety-toolkit",
    title: "ASAN Autism & Safety Toolkit",
    summary:
      "A self-advocate-created resource covering safety, community inclusion, autonomy, bullying, mental health, and support for families.",
    collectionName: "Adult Independence",
    category: "Self-advocacy",
    audience: "Autistic people, families, and supporters",
    ageGroup: "adult",
    tags: ["independent-living", "social-growth", "caregiver-wellness"],
    locationScope: "Available nationwide",
    verified: true,
    organization: "Autistic Self Advocacy Network",
    href: "https://autisticadvocacy.org/policy/toolkits/safety/",
    regionTags: ["nationwide"],
  },
  {
    id: "spectrum-gaming-community",
    title: "Spectrum Gaming",
    summary:
      "An autistic-led online gaming community with youth-centered support, community events, and social connection built around shared interests.",
    collectionName: "Online Play and Community",
    category: "Gaming",
    audience: "Autistic young people, teens, and families",
    ageGroup: "teen",
    tags: ["social-growth", "independent-living", "caregiver-wellness"],
    locationScope: "Online community with region-specific enrollment details",
    verified: true,
    organization: "Spectrum Gaming",
    href: "https://www.spectrumgaming.net/faqs",
    regionTags: ["virtual", "nationwide"],
  },
  {
    id: "pbs-kids-games",
    title: "PBS KIDS Games",
    summary:
      "Free PBS KIDS games families can use at home for low-pressure play, routine building, and learning through familiar characters.",
    collectionName: "Online Play and Community",
    category: "Play and games",
    audience: "Young children, school-age children, and caregivers",
    ageGroup: "school-age",
    tags: ["education", "social-growth", "sensory-support"],
    locationScope: "Available online nationwide",
    verified: true,
    organization: "PBS KIDS",
    href: "https://pbskids.org/games",
    regionTags: ["virtual", "nationwide"],
  },
  {
    id: "pbs-spectrum-story-of-the-mind",
    title: "PBS Spectrum: A Story of the Mind",
    summary:
      "A PBS video collection that can help families, educators, and community members better understand autism through real stories and perspectives.",
    collectionName: "PBS and Video Picks",
    category: "PBS videos",
    audience: "Families, self-advocates, educators, and supporters",
    ageGroup: "all",
    tags: ["education", "social-growth", "caregiver-wellness"],
    locationScope: "Available online nationwide",
    verified: true,
    organization: "PBS",
    href: "https://www.pbs.org/video/spectrum-story-mind-spectrum-kids/",
    regionTags: ["virtual", "nationwide"],
  },
  {
    id: "pbs-kids-videos",
    title: "PBS KIDS Videos",
    summary:
      "PBS KIDS videos families can reach quickly for calm screen time, shared learning, and familiar routines at home.",
    collectionName: "PBS and Video Picks",
    category: "PBS videos",
    audience: "Young children, school-age children, and caregivers",
    ageGroup: "school-age",
    tags: ["education", "sensory-support", "social-growth"],
    locationScope: "Available online nationwide",
    verified: true,
    organization: "PBS KIDS",
    href: "https://pbskids.org/videos",
    regionTags: ["virtual", "nationwide"],
  },
  {
    id: "autism-navigator-family-resources",
    title: "Autism Navigator Family Resources",
    summary:
      "Evidence-informed family courses, videos, and autism learning tools that help caregivers support everyday development from home.",
    collectionName: "Learning at Home",
    category: "Learning tools",
    audience: "Parents, caregivers, and early childhood support teams",
    ageGroup: "early-years",
    tags: ["early-support", "education", "caregiver-wellness"],
    locationScope: "Available online nationwide",
    verified: true,
    organization: "Autism Navigator",
    href: "https://autismnavigator.com/",
    regionTags: ["virtual", "nationwide"],
  },
  {
    id: "khan-academy-kids",
    title: "Khan Academy Kids",
    summary:
      "A free early learning app families can use for reading, math, creativity, and social-emotional practice at home.",
    collectionName: "Learning at Home",
    category: "Learning tools",
    audience: "Young children, school-age children, and caregivers",
    ageGroup: "early-years",
    tags: ["education", "social-growth", "sensory-support"],
    locationScope: "Available online nationwide",
    verified: true,
    organization: "Khan Academy Kids",
    href: "https://learn.khanacademy.org/khan-academy-kids/",
    regionTags: ["virtual", "nationwide"],
  },
  {
    id: "california-ihss-program",
    title: "California IHSS Program",
    summary:
      "The official California In-Home Supportive Services page for families exploring support that can help a child or disabled family member stay safely at home.",
    collectionName: "Caregiver Applications",
    category: "Caregiver benefits",
    audience: "Parents, caregivers, and at-home support teams",
    ageGroup: "caregiver",
    tags: ["caregiver-wellness", "independent-living", "early-support"],
    locationScope: "California program with county-level application steps",
    verified: true,
    organization: "California Department of Social Services",
    href: "https://cdss.ca.gov/in-home-supportive-services",
    regionTags: ["california"],
  },
  {
    id: "california-dds-early-start",
    title: "California DDS Early Start",
    summary:
      "Official California developmental services information families can use when exploring early intervention pathways and regional center support.",
    collectionName: "Caregiver Applications",
    category: "Caregiver benefits",
    audience: "Parents, caregivers, and young children",
    ageGroup: "early-years",
    tags: ["early-support", "education", "caregiver-wellness"],
    locationScope: "California early intervention program information",
    verified: true,
    organization: "California Department of Developmental Services",
    href: "https://www.dds.ca.gov/services/early-start/laws-and-regulations/",
    regionTags: ["california"],
  },
  {
    id: "ssa-ssi-for-children",
    title: "SSA SSI for Children",
    summary:
      "Social Security's official SSI information for children with disabilities, including what families may need before beginning the application process.",
    collectionName: "Caregiver Applications",
    category: "Caregiver benefits",
    audience: "Parents and caregivers",
    ageGroup: "caregiver",
    tags: ["caregiver-wellness", "independent-living", "early-support"],
    locationScope: "Available nationwide",
    verified: true,
    organization: "Social Security Administration",
    href: "https://www.ssa.gov/ssi/text-understanding-ssi.htm",
    regionTags: ["nationwide"],
  },
  {
    id: "california-paid-family-leave",
    title: "California Paid Family Leave",
    summary:
      "Official California paid family leave information for caregivers who may need short-term wage replacement while supporting family needs at home.",
    collectionName: "Caregiver Applications",
    category: "Caregiver benefits",
    audience: "Parents, caregivers, and working family members",
    ageGroup: "caregiver",
    tags: ["caregiver-wellness", "independent-living"],
    locationScope: "California wage-replacement benefit information",
    verified: true,
    organization: "California Employment Development Department",
    href: "https://edd.ca.gov/en/disability/Calculating_PFL_Benefit_Payment_Amounts",
    regionTags: ["california"],
  },
  {
    id: "sensory-safe-solution-provider-finder",
    title: "The Sensory Safe Solution Provider Finder",
    summary:
      "A nationwide starting point for finding sensory-safe barbers, stylists, and salons that are building haircut experiences around regulation, communication, and comfort.",
    collectionName: "Haircuts and Grooming",
    category: "Provider finder",
    audience: "Autistic people, families, caregivers, and adults",
    ageGroup: "all",
    tags: ["sensory-support", "caregiver-wellness", "social-growth"],
    locationScope: "Nationwide provider network with location-based search",
    verified: true,
    organization: "The Sensory Safe Solution",
    href: "https://www.thesensorysafesolution.org/",
    regionTags: ["nationwide"],
  },
  {
    id: "autism-speaks-haircutting-training-guide",
    title: "Autism Speaks Haircutting Training Guide",
    summary:
      "A family-friendly haircut prep guide with salon tips, a visual schedule, and planning ideas that can make grooming visits feel more predictable and less stressful.",
    collectionName: "Haircuts and Grooming",
    category: "Preparation guide",
    audience: "Parents, caregivers, stylists, and autistic people",
    ageGroup: "all",
    tags: ["sensory-support", "caregiver-wellness", "education"],
    locationScope: "Available online nationwide",
    verified: true,
    organization: "Autism Speaks",
    href: "https://www.autismspeaks.org/tool-kit/haircutting-training-guide",
    regionTags: ["virtual", "nationwide"],
  },
  {
    id: "autism-society-san-diego-hair-salon-directory",
    title: "Autism Society San Diego Hair Salon Directory",
    summary:
      "A Southern California directory page focused on haircut and salon support, including local autism-aware providers, contact details, and age ranges served.",
    collectionName: "Haircuts and Grooming",
    category: "Local directory",
    audience: "Children, adults, families, and caregivers",
    ageGroup: "all",
    tags: ["sensory-support", "caregiver-wellness", "social-growth"],
    locationScope: "San Diego and Southern California",
    verified: true,
    organization: "Autism Society San Diego",
    href: "https://www.autismsocietysandiego.org/map-category/hair-salon",
    regionTags: ["southern-california", "california"],
  },
  {
    id: "bubble-cuts-los-angeles",
    title: "Bubble Cuts Los Angeles Locations",
    summary:
      "A Los Angeles-area children's salon with Studio City, Eagle Rock, and Montrose locations, plus kid-focused seating, screens, and patient stylists that can help some families create a calmer haircut routine.",
    collectionName: "Haircuts and Grooming",
    category: "Local salon",
    audience: "Babies, children, and caregivers",
    ageGroup: "school-age",
    tags: ["sensory-support", "caregiver-wellness", "social-growth"],
    locationScope: "Studio City, Eagle Rock, and Montrose in Los Angeles County",
    verified: true,
    organization: "Bubble Cuts",
    href: "https://www.bubblecuts.com/",
    regionTags: ["los-angeles-county", "southern-california", "california"],
  },
  {
    id: "cde-reasons-for-concern",
    title: "California Reasons for Concern",
    summary:
      "A California starting point for families who want to ask for help through their school district or local early support system, including when written parent consent is needed for assessment and services.",
    collectionName: "California School and Insurance Help",
    category: "School evaluation",
    audience: "Parents, caregivers, and families seeking school support",
    ageGroup: "caregiver",
    tags: ["education", "early-support", "caregiver-wellness"],
    locationScope: "California statewide school district and early support guidance",
    verified: true,
    organization: "California Department of Education",
    href: "https://www.cde.ca.gov/sp/se/fp/concerns.asp",
    regionTags: ["california"],
  },
  {
    id: "cde-parents-rights-special-education",
    title: "California Parents' Rights in Special Education",
    summary:
      "An official family guide to consent, assessments, IEP participation, nondiscriminatory testing, and the rights parents have when working with the school district.",
    collectionName: "California School and Insurance Help",
    category: "Parents' rights",
    audience: "Parents, caregivers, and advocates",
    ageGroup: "caregiver",
    tags: ["education", "caregiver-wellness"],
    locationScope: "California statewide special education guidance",
    verified: true,
    organization: "California Department of Education",
    href: "https://www.cde.ca.gov/sp/se/qa/pssummary.asp",
    regionTags: ["california"],
  },
  {
    id: "cde-independent-educational-evaluations",
    title: "California Independent Educational Evaluations",
    summary:
      "If you disagree with a school district evaluation, this California guidance explains the right to ask for an independent educational evaluation at public expense.",
    collectionName: "California School and Insurance Help",
    category: "Independent evaluations",
    audience: "Parents, caregivers, and advocates",
    ageGroup: "caregiver",
    tags: ["education", "caregiver-wellness"],
    locationScope: "California statewide",
    verified: true,
    organization: "California Department of Education",
    href: "https://www.cde.ca.gov/sp/se/lr/om031121.asp",
    regionTags: ["california"],
  },
  {
    id: "california-autism-insurance-coverage",
    title: "California Autism Insurance Coverage",
    summary:
      "An official California insurance page covering autism treatment access, behavioral health treatment rules, and complaint pathways when coverage is delayed or denied.",
    collectionName: "California School and Insurance Help",
    category: "Insurance coverage",
    audience: "Parents, caregivers, and families seeking treatment coverage",
    ageGroup: "caregiver",
    tags: ["early-support", "caregiver-wellness", "sensory-support"],
    locationScope: "California statewide insurance guidance",
    verified: true,
    organization: "California Department of Insurance",
    href: "https://www.insurance.ca.gov/01-consumers/110-health/60-resources/05-autism/",
    regionTags: ["california"],
  },
  {
    id: "california-dmhc-behavioral-health-care",
    title: "California Behavioral Health Care Rights",
    summary:
      "The state's managed care guide to behavioral health treatment, how to get care, and what families can do if a health plan will not approve medically necessary autism support.",
    collectionName: "California School and Insurance Help",
    category: "Insurance rights",
    audience: "Families with HMO or managed care coverage",
    ageGroup: "caregiver",
    tags: ["early-support", "caregiver-wellness", "sensory-support"],
    locationScope: "California statewide health plan guidance",
    verified: true,
    organization: "California Department of Managed Health Care",
    href: "https://www.dmhc.ca.gov/HealthCareinCalifornia/GettheBestCare/BehavioralHealthCare.aspx",
    regionTags: ["california"],
  },
  {
    id: "autism-speaks-iep-guide",
    title: "Autism Speaks Guide to Individualized Education Programs",
    summary:
      "A family-friendly walkthrough of the IEP process that can help you prepare for school meetings, paperwork, and next steps after assessment.",
    collectionName: "California School and Insurance Help",
    category: "IEP planning",
    audience: "Parents, caregivers, and school teams",
    ageGroup: "caregiver",
    tags: ["education", "caregiver-wellness"],
    locationScope: "Available nationwide",
    verified: true,
    organization: "Autism Speaks",
    href: "https://www.autismspeaks.org/tool-kit/guide-individualized-education-programs-iep",
    regionTags: ["nationwide"],
  },
  {
    id: "autism-in-black",
    title: "Autism in Black",
    summary:
      "A neurodivergent-led organization offering culturally responsive education, advocacy, and support for Black autistic people and their families.",
    collectionName: "Family and Caregivers",
    category: "Community support",
    audience: "Black autistic people, families, and allies",
    ageGroup: "all",
    tags: ["social-growth", "caregiver-wellness", "education"],
    locationScope: "Online support with nationwide reach",
    verified: true,
    organization: "Autism in Black",
    href: "https://www.autisminblack.org/",
    regionTags: ["virtual", "nationwide"],
  },
  {
    id: "disneyland-disability-access-service",
    title: "Disneyland Disability Access Service",
    summary:
      "Disneyland's official DAS page for guests who, due to a developmental disability like autism or similar, cannot wait in a conventional queue for an extended period of time.",
    collectionName: "Theme Parks and Outings",
    category: "Access pass",
    audience: "Families, self-advocates, and support teams",
    ageGroup: "all",
    tags: ["sensory-support", "social-growth", "caregiver-wellness"],
    locationScope: "Disneyland Resort in Anaheim, California",
    verified: true,
    organization: "Disneyland Resort",
    href: "https://disneyland.disney.go.com/en-ca/guest-services/disability-access-service/",
    regionTags: ["orange-county", "southern-california", "california"],
  },
  {
    id: "disneyland-baby-care-centers",
    title: "Disneyland Baby Care Centers",
    summary:
      "Official Disneyland baby care information with locations for diaper changes, nursing, feeding, and calmer care support during a park day.",
    collectionName: "Theme Parks and Outings",
    category: "Quiet and nursing support",
    audience: "Parents, caregivers, and families with younger children",
    ageGroup: "caregiver",
    tags: ["sensory-support", "caregiver-wellness"],
    locationScope: "Disneyland Resort in Anaheim, California",
    verified: true,
    organization: "Disneyland Resort",
    href: "https://disneyland.disney.go.com/en_CA/guest-services/baby-center-lost-children/",
    regionTags: ["orange-county", "southern-california", "california"],
  },
  {
    id: "disneyland-resort-maps",
    title: "Disneyland Resort Maps",
    summary:
      "Use Disneyland's official map to find guest services, restrooms, baby care, first aid, attractions, and places to take a breather before you arrive.",
    collectionName: "Theme Parks and Outings",
    category: "Park maps",
    audience: "Families, self-advocates, and support teams",
    ageGroup: "all",
    tags: ["sensory-support", "social-growth"],
    locationScope: "Disneyland Resort in Anaheim, California",
    verified: true,
    organization: "Disneyland Resort",
    href: "https://disneyland.disney.go.com/en/maps/",
    regionTags: ["orange-county", "southern-california", "california"],
  },
  {
    id: "legoland-california-autism-support",
    title: "LEGOLAND California Autism Support",
    summary:
      "LEGOLAND California's autism support page helps families plan for sensory needs, rider access, and the support options available before a visit.",
    collectionName: "Theme Parks and Outings",
    category: "Access pass",
    audience: "Families and autistic guests",
    ageGroup: "all",
    tags: ["sensory-support", "social-growth", "caregiver-wellness"],
    locationScope: "LEGOLAND California Resort in Carlsbad, California",
    verified: true,
    organization: "LEGOLAND California Resort",
    href: "https://california-support.legoland.com/hc/en-us/articles/25007290318493-How-does-LEGOLAND-California-Resort-support-guests-with-autism",
    regionTags: ["san-diego-county", "southern-california", "california"],
  },
  {
    id: "legoland-california-accessibility-information",
    title: "LEGOLAND California Accessibility Information",
    summary:
      "An official planning page for accessibility services, rider requirements, and visit support before a LEGOLAND California day out.",
    collectionName: "Theme Parks and Outings",
    category: "Visit planning",
    audience: "Families, self-advocates, and support teams",
    ageGroup: "all",
    tags: ["sensory-support", "social-growth"],
    locationScope: "LEGOLAND California Resort in Carlsbad, California",
    verified: true,
    organization: "LEGOLAND California Resort",
    href: "https://www.legoland.com/california/plan-your-visit/know-before-you-go/accessibility-information/",
    regionTags: ["san-diego-county", "southern-california", "california"],
  },
  {
    id: "universal-studios-hollywood-accessibility-guide",
    title: "Universal Studios Hollywood Accessibility Guide",
    summary:
      "Universal Studios Hollywood's official accessibility guide covers boarding needs, ride information, stroller and wheelchair questions, and planning support before you go.",
    collectionName: "Theme Parks and Outings",
    category: "Visit planning",
    audience: "Families, self-advocates, and support teams",
    ageGroup: "all",
    tags: ["sensory-support", "social-growth"],
    locationScope: "Universal Studios Hollywood in Los Angeles County",
    verified: true,
    organization: "Universal Studios Hollywood",
    href: "https://www.universalstudioshollywood.com/web/en/us/plan-your-visit/accessibility-guide",
    regionTags: ["los-angeles-county", "southern-california", "california"],
  },
  {
    id: "seaworld-san-diego-accessibility-guide",
    title: "SeaWorld San Diego Accessibility Guide",
    summary:
      "SeaWorld San Diego's official accessibility guide includes services, attractions, and visit planning details for guests who need extra support.",
    collectionName: "Theme Parks and Outings",
    category: "Visit planning",
    audience: "Families, self-advocates, and support teams",
    ageGroup: "all",
    tags: ["sensory-support", "social-growth"],
    locationScope: "SeaWorld San Diego in San Diego County",
    verified: true,
    organization: "SeaWorld San Diego",
    href: "https://seaworld.com/san-diego/-/media/migrated-media/seaworld-san-diego/files/pdf/swc-accessibility-guide-102824.pdf",
    regionTags: ["san-diego-county", "southern-california", "california"],
  },
  {
    id: "we-rock-the-spectrum-open-play",
    title: "We Rock the Spectrum Open Play",
    summary:
      "A sensory-safe indoor play option with open play, calming spaces, and movement-based equipment designed so more children can participate comfortably.",
    collectionName: "Spectrum-Friendly Playplaces",
    category: "Indoor gym",
    audience: "Children, siblings, and caregivers",
    ageGroup: "school-age",
    tags: ["sensory-support", "social-growth", "caregiver-wellness"],
    locationScope: "Available by location",
    verified: true,
    organization: "We Rock the Spectrum Kid's Gym",
    href: "https://www.werockthespectrumkidsgym.com/open-play/",
    regionTags: ["nationwide"],
  },
  {
    id: "we-rock-the-spectrum-locations",
    title: "We Rock the Spectrum Locations",
    summary:
      "Browse locations for a sensory-friendly kids gym built around play, movement, and inclusive family visits.",
    collectionName: "Spectrum-Friendly Playplaces",
    category: "Location finder",
    audience: "Children, families, and caregivers",
    ageGroup: "school-age",
    tags: ["sensory-support", "social-growth"],
    locationScope: "Nationwide location finder",
    verified: true,
    organization: "We Rock the Spectrum Kid's Gym",
    href: "https://www.werockthespectrumkidsgym.com/locations/",
    regionTags: ["nationwide"],
  },
  {
    id: "sky-zone-sensory-hours",
    title: "Sky Zone Sensory Hours",
    summary:
      "A quieter trampoline-park session with toned-down sound and a more comfortable environment for guests with sensory needs.",
    collectionName: "Spectrum-Friendly Playplaces",
    category: "Sensory hours",
    audience: "Children, teens, and families",
    ageGroup: "school-age",
    tags: ["sensory-support", "social-growth"],
    locationScope: "Available at participating Sky Zone parks",
    verified: true,
    organization: "Sky Zone",
    href: "https://www.skyzone.com/programs/sensory-hours/",
    regionTags: ["nationwide"],
  },
  {
    id: "chuck-e-cheese-sensory-sensitive-sundays",
    title: "Chuck E. Cheese Sensory Sensitive Sundays",
    summary:
      "A calmer Chuck E. Cheese experience with dimmed lights, lower volume, and early-hours play for families who want a softer outing.",
    collectionName: "Spectrum-Friendly Playplaces",
    category: "Sensory hours",
    audience: "Children and families",
    ageGroup: "school-age",
    tags: ["sensory-support", "social-growth"],
    locationScope: "Available at participating Chuck E. Cheese locations",
    verified: true,
    organization: "Chuck E. Cheese",
    href: "https://www.chuckecheese.com/cupertino-ca/sensory-sensitive-sundays/participating-locations/",
    regionTags: ["nationwide"],
  },
  {
    id: "kulturecity-sensory-inclusive-venues",
    title: "KultureCity Sensory Inclusive Venues",
    summary:
      "A place to look for venues, events, and businesses that have sensory-inclusive supports in place before you head out.",
    collectionName: "Spectrum-Friendly Playplaces",
    category: "Venue finder",
    audience: "Families, self-advocates, and support teams",
    ageGroup: "all",
    tags: ["sensory-support", "social-growth", "caregiver-wellness"],
    locationScope: "Nationwide venue network",
    verified: true,
    organization: "KultureCity",
    href: "https://www.kulturecity.org/",
    regionTags: ["nationwide"],
  },
  {
    id: "proloquo2go",
    title: "Proloquo2Go",
    summary:
      "A widely used AAC app families can explore when a child or adult needs speech support, language modeling, or another way to communicate more clearly.",
    collectionName: "Sensory Tools and Communication",
    category: "AAC app",
    audience: "Children, adults, families, and speech teams",
    ageGroup: "all",
    tags: ["education", "social-growth", "independent-living"],
    locationScope: "Available by app purchase",
    verified: true,
    organization: "AssistiveWare",
    href: "https://www.assistiveware.com/products/proloquo2go",
    regionTags: ["nationwide"],
  },
  {
    id: "td-snap",
    title: "TD Snap",
    summary:
      "An AAC app with multiple page sets, touch and switch access, and family-friendly tools for building communication support.",
    collectionName: "Sensory Tools and Communication",
    category: "AAC app",
    audience: "Children, adults, families, and speech teams",
    ageGroup: "all",
    tags: ["education", "social-growth", "independent-living"],
    locationScope: "Available for iPad, Windows, and supported devices",
    verified: true,
    organization: "Tobii Dynavox",
    href: "https://www.tobiidynavox.com/products/td-snap/",
    regionTags: ["nationwide"],
  },
  {
    id: "boardmaker",
    title: "Boardmaker",
    summary:
      "A symbol-based tool families and educators often use to create visual supports, schedules, and communication materials for home and school.",
    collectionName: "Sensory Tools and Communication",
    category: "Visual supports",
    audience: "Families, educators, and support teams",
    ageGroup: "all",
    tags: ["education", "social-growth", "caregiver-wellness"],
    locationScope: "Available online",
    verified: true,
    organization: "Tobii Dynavox",
    href: "https://www.tobiidynavox.com/products/boardmaker/",
    regionTags: ["nationwide"],
  },
  {
    id: "autism-speaks-visual-supports",
    title: "Autism Speaks Visual Supports and Autism Guide",
    summary:
      "A family guide to using visual supports for daily routines, transitions, communication, and predictability at home or in school.",
    collectionName: "Sensory Tools and Communication",
    category: "Visual supports",
    audience: "Parents, caregivers, and educators",
    ageGroup: "all",
    tags: ["education", "sensory-support", "caregiver-wellness"],
    locationScope: "Available online nationwide",
    verified: true,
    organization: "Autism Speaks",
    href: "https://www.autismspeaks.org/tool-kit/atnair-p-visual-supports-and-autism",
    regionTags: ["nationwide"],
  },
  {
    id: "autism-speaks-sensory-issues",
    title: "Autism Speaks Sensory Issues Guide",
    summary:
      "A practical guide to sensory differences that can help families think through sound, touch, movement, and daily regulation needs.",
    collectionName: "Sensory Tools and Communication",
    category: "Sensory guide",
    audience: "Families, self-advocates, and supporters",
    ageGroup: "all",
    tags: ["sensory-support", "caregiver-wellness", "education"],
    locationScope: "Available online nationwide",
    verified: true,
    organization: "Autism Speaks",
    href: "https://www.autismspeaks.org/sensory-issues",
    regionTags: ["nationwide"],
  },
  {
    id: "tangle-braintools",
    title: "Tangle BrainTools",
    summary:
      "A fidget option families can browse when they want something twistable and hand-based for focus, movement, or quiet regulation support.",
    collectionName: "Sensory Tools and Communication",
    category: "Fidgets",
    audience: "Children, teens, adults, and families",
    ageGroup: "all",
    tags: ["sensory-support", "social-growth"],
    locationScope: "Available online",
    verified: true,
    organization: "Tangle Creations",
    href: "https://www.tanglecreations.com/collections/tangle-brain-tools/relax-therapy",
    regionTags: ["nationwide"],
  },
  {
    id: "southpaw-disc-swing",
    title: "Southpaw Disc Swing",
    summary:
      "A movement tool families and therapists may consider when a child seeks spinning, vestibular input, and full-body sensory play.",
    collectionName: "Sensory Tools and Communication",
    category: "Movement tools",
    audience: "Families, therapists, and support teams",
    ageGroup: "school-age",
    tags: ["sensory-support", "social-growth"],
    locationScope: "Available online",
    verified: true,
    organization: "Southpaw",
    href: "https://www.southpaw.com/disc-swing/",
    regionTags: ["nationwide"],
  },
  {
    id: "nugget-play-couch",
    title: "Nugget Play Couch",
    summary:
      "A soft play couch families often use for forts, deep-pressure style cozy setups, gross motor play, and quieter indoor movement days.",
    collectionName: "Sensory Tools and Communication",
    category: "Play furniture",
    audience: "Children and caregivers",
    ageGroup: "school-age",
    tags: ["sensory-support", "social-growth"],
    locationScope: "Available online",
    verified: true,
    organization: "Nugget",
    href: "https://nuggetcomfort.com/products/the-nugget-fairway",
    regionTags: ["nationwide"],
  },
  {
    id: "lakeshore-sensory-development",
    title: "Lakeshore Sensory Development Collection",
    summary:
      "A browseable collection of sensory balls, poppers, tactile toys, and early play tools families can look through when building a calmer home setup.",
    collectionName: "Sensory Tools and Communication",
    category: "Play tools",
    audience: "Young children, school-age children, and caregivers",
    ageGroup: "early-years",
    tags: ["sensory-support", "social-growth", "education"],
    locationScope: "Available online and in stores",
    verified: true,
    organization: "Lakeshore Learning",
    href: "https://www.lakeshorelearning.com/products/infants-toddlers/sensory-development/N/2136324428/",
    regionTags: ["nationwide"],
  },
];

export const eventSeeds = [
  {
    id: "jump-4-autism-2026",
    title: "Jump 4 Autism",
    detail:
      "A Southern California family event with jumping, climbing, arts and crafts, and time to connect with other autism families.",
    audience: "Parents, caregivers, and children",
    format: "In person",
    eventDate: "2026-04-18T09:00:00-07:00",
    hostName: "The Autism Community in Action",
    location: "Sky Zone, Santa Ana, California",
    href: "https://tacanow.org/what-we-do/socal-outreach/",
    regionTags: ["orange-county", "southern-california", "california"],
  },
  {
    id: "taca-virtual-support-teens-and-adults-2026",
    title: "Virtual Support Event - Teens and Adults",
    detail:
      "A one-hour Zoom support event for parents and caregivers of teens or adults with autism who want guidance, shared problem-solving, and community.",
    audience: "Parents and caregivers of teens and adults",
    format: "Virtual",
    eventDate: "2026-04-29T16:00:00-07:00",
    hostName: "The Autism Community in Action",
    location: "Online via Zoom",
    href: "https://tacanow.org/monthly-learning-series-gi-issues/",
    regionTags: ["virtual", "nationwide"],
  },
  {
    id: "seesaw-connect-2026",
    title: "Seesaw Connect",
    detail:
      "A casual coffee meet-up for parents and caregivers to swap resources, share stories, and build local encouragement.",
    audience: "Parents and caregivers",
    format: "In person",
    eventDate: "2026-04-30T10:00:00-07:00",
    hostName: "The Autism Community in Action",
    location: "Seesaw Beans and Coffee, Buena Park, California",
    href: "https://tacanow.org/event/seesaw-connect-013024/",
    regionTags: ["orange-county", "southern-california", "california"],
  },
  {
    id: "nlacrc-self-determination-orientation-2026",
    title: "Self-Determination Orientation",
    detail:
      "An orientation for people who want to learn more about California's Self-Determination Program and how it can support more individualized planning.",
    audience: "Adults, families, and self-advocates",
    format: "Virtual",
    eventDate: "2026-05-04T13:00:00-07:00",
    hostName: "North Los Angeles County Regional Center",
    location: "Online",
    href: "https://www.nlacrc.org/calendar/self-determination-orientation-18/",
    regionTags: ["virtual", "antelope-valley", "los-angeles-county", "california"],
  },
  {
    id: "nlacrc-rainbow-connection-2026",
    title: "Rainbow Connection Social Group",
    detail:
      "A recurring Zoom social group listed by NLACRC for connection, conversation, and community building.",
    audience: "Autistic adults and community members",
    format: "Virtual",
    eventDate: "2026-05-19T18:30:00-07:00",
    hostName: "North Los Angeles County Regional Center",
    location: "Online",
    href: "https://www.nlacrc.org/calendar/rainbow-connection-social-group-12/2026-08-18/",
    regionTags: ["virtual", "los-angeles-county", "california"],
  },
  {
    id: "community-navigator-meet-and-greet",
    title: "Community Navigator Meet and Greet",
    detail:
      "Meet regional community navigators and get help with IHSS, Medi-Cal, regional center services, and local resources in the Antelope Valley.",
    audience: "Families and caregivers",
    format: "In person",
    eventDate: "2026-09-11T10:00:00-07:00",
    hostName: "Family Focus Resource Center and NLACRC",
    location: "Ohana Center, Palmdale, California",
    href: "https://www.nlacrc.org/calendar/%F0%9F%8C%9F-community-navigator-meet-greet-%F0%9F%8C%9F-hosted-by-family-focus-resource-center/",
    regionTags: ["antelope-valley", "los-angeles-county", "southern-california", "california"],
  },
];

export const professionalSeeds: ProfessionalRecord[] = [
  {
    id: "family-focus-resource-center-provider",
    name: "Family Focus Resource Center",
    title: "Family resource and empowerment center",
    focus: "Parent mentoring, IEP support, family workshops, and navigation",
    organization: "CSUN Family Focus Resource Center",
    location: "Antelope Valley, San Fernando Valley, and Santa Clarita, California",
    summary:
      "Supports families with special education guidance, workshops, support groups, and practical navigation help across several Los Angeles County regions.",
    acceptingNewFamilies: true,
    verified: true,
    href: "https://www.californiafamilyempowermentcenters.org/spotlight-FamilyFocus.html",
    regionTags: [
      "antelope-valley",
      "los-angeles-county",
      "southern-california",
      "california",
    ],
  },
  {
    id: "easterseals-socal-provider",
    name: "Easterseals Southern California Autism Services",
    title: "Regional autism service provider",
    focus: "Family services, developmental supports, and autism programming",
    organization: "Easterseals Southern California",
    location: "Southern California",
    summary:
      "Provides autism-related services, family support, and broader disability programs across Southern California.",
    acceptingNewFamilies: true,
    verified: true,
    href: "https://www.easterseals.com/southerncal/support-and-education/autism/index-1.html",
    regionTags: ["southern-california", "orange-county", "california"],
  },
  {
    id: "nlacrc-community-support-provider",
    name: "North Los Angeles County Regional Center",
    title: "Regional center support and advocacy hub",
    focus: "Support groups, community partnerships, and service navigation",
    organization: "North Los Angeles County Regional Center",
    location: "North Los Angeles County and Antelope Valley, California",
    summary:
      "Helps families and self-advocates connect with support groups, advocacy partners, and regional service pathways.",
    acceptingNewFamilies: true,
    verified: true,
    href: "https://www.nlacrc.org/get-involved/advocacy/partners-advocacy-groups/",
    regionTags: [
      "antelope-valley",
      "los-angeles-county",
      "southern-california",
      "california",
    ],
  },
  {
    id: "autism-speaks-art-provider",
    name: "Autism Speaks Autism Response Team",
    title: "National information and navigation support",
    focus: "Resource matching, tool kits, and next-step guidance",
    organization: "Autism Speaks",
    location: "Nationwide",
    summary:
      "Connects autistic people, families, and caregivers with information, resources, and support options across the United States.",
    acceptingNewFamilies: true,
    verified: true,
    href: "https://www.autismspeaks.org/family-services",
    regionTags: ["nationwide"],
  },
  {
    id: "taca-family-support-provider",
    name: "The Autism Community in Action",
    title: "Parent support and education network",
    focus: "Parent mentorship, support events, and practical autism education",
    organization: "The Autism Community in Action",
    location: "Nationwide with Southern California events",
    summary:
      "Offers family support events, webinars, and parent-focused resources designed to reduce isolation and strengthen confidence.",
    acceptingNewFamilies: true,
    verified: true,
    href: "https://tacanow.org/way-to-help/be-a-member/",
    regionTags: ["nationwide", "southern-california", "california"],
  },
];

export const communityPostSeeds = [
  {
    id: "seed-post-1",
    authorName: "Ryan S.",
    authorRole: "Parent of a 9-year-old",
    topic: "Sensory and Lifestyle",
    tag: "Helpful Tips",
    title: "Does anyone have advice for managing sensory overload in tennis?",
    body:
      "We want to keep the activity joyful, but the noise and transitions are getting tough. Would love strategies that helped your family.",
    createdAt: "2026-04-12T17:00:00.000Z",
  },
  {
    id: "seed-post-2",
    authorName: "Maya L.",
    authorRole: "Autistic college student",
    topic: "Self-Advocacy",
    tag: "Self-Advocacy",
    title: "Best ways to explain accommodation needs to a new professor",
    body:
      "I want to advocate for myself clearly without feeling like I have to over-disclose. Curious what language has worked for others.",
    createdAt: "2026-04-12T13:30:00.000Z",
  },
  {
    id: "seed-post-3",
    authorName: "Jordan K.",
    authorRole: "Occupational therapist",
    topic: "School and Therapy",
    tag: "Verified Guidance",
    title: "Small environment shifts that can lower after-school stress",
    body:
      "A few calming transitions can make evenings easier. Sharing routines families have reported as especially practical and sustainable.",
    createdAt: "2026-04-11T18:15:00.000Z",
  },
];
